module.exports = {
    USER_DETAILS: 'USER_DETAILS',
    USER_IS_LOGGED: 'USER_IS_LOGGED',
    USER_IS_NOT_LOGGED: 'USER_IS_NOT_LOGGED',
    USER_LOGIN_SUCESS: 'USER_LOGIN_SUCESS',
    USER_LOGOUT_SUCESS: 'USER_LOGOUT_SUCESS'
};
