module.exports = {
    USER_DETAILS: 'USER_DETAILS',
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
    USER_LOGIN_SUCESS: 'USER_LOGIN_SUCESS',
    USER_LOGOUT_SUCESS: 'USER_LOGOUT_SUCESS',
    USER_IS_LOGGED: 'USER_IS_LOGGED',
    USER_IS_NOT_LOGGED: 'USER_IS_NOT_LOGGED',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_REGISTERED: 'USER_REGISTERED',
    USER_REGISTER_ERROR: 'USER_REGISTER_ERROR'
};
