module.exports = {
    APP_CREATED: 'APP_CREATED',
    APP_LIST_LOADED: 'APP_LIST_LOADED',
    APP_SEARCH_LOADED: 'APP_SEARCH_LOADED',
    APP_INFO_LOADED: 'APP_INFO_LOADED',
    APP_META_UPDATED: 'APP_META_UPDATED'
};
