module.exports = {
    QUIZZES_LOADED: 'QUIZZES_LOADED',
    QUIZZES_PUBLIC_LOADED: 'QUIZZES_PUBLIC_LOADED',
    QUIZZES_PUBLIC_QUERIED: 'QUIZZES_PUBLIC_QUERIED',
    QUIZ_ADDED: 'QUIZ_ADDED',
    QUIZ_META_UPDATED: 'QUIZ_META_UPDATED',
    QUIZ_DELETED: 'QUIZ_DELETED',
    QUIZ_LOADED: 'QUIZ_LOADED',
    QUIZ_PUBLIC_LOADED: 'QUIZ_PUBLIC_LOADED',
    QUIZ_CHANGED: 'QUIZ_CHANGED',
    TOPICS_LOADED: 'TOPICS_LOADED'
};
