module.exports = {
    QUIZZES_LOADED: 'QUIZZES_LOADED',
    QUIZZES_PUBLIC_LOADED: 'QUIZZES_PUBLIC_LOADED',
    QUIZ_ADDED: 'QUIZ_ADDED',
    QUIZ_LOADED: 'QUIZ_LOADED',
    TOPICS_LOADED: 'TOPICS_LOADED'
};
