module.exports = {
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCESS: 'USER_LOGIN_SUCESS',
    USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_IS_LOGGED: 'USER_IS_LOGGED',
    USER_IS_NOT_LOGGED: 'USER_IS_NOT_LOGGED',
    USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED'
};
